### PR TITLE
Unable to load the DayZSynthesizer after saving it

### LINKED ISSUE #2698: Unable to load the DayZSynthesizer after saving it
### Environment Details
* SDV version: 1.27.0 (with SDV Enterprise version 0.34.0)
* Python version: 3.12
* Operating System: MacOS

### Error Description
After saving a DayZSynthesizer object (either single or multi-table), I'm not able to load it back in using the new [loading utility function](https://docs.sdv.dev/sdv/multi-table-data/modeling/synthesizers/hsasynthesizer#load-utility-function) that we introduced in #2619.

### Steps to reproduce
This works with single or multi-table DayZSynthesizer, using any metadata.

```python
from sdv.datasets.demo import download_demo
from sdv.multi_table import DayZSynthesizer
from sdv.utils import load_synthesizer

_, metadata = download_demo(
    modality='multi_table',
    dataset_name='fake_hotels')

# create and save a synthesizer
synthesizer = DayZSynthesizer(metadata)
synthesizer.save('my_synthesizer.pkl')

# try to load it back from the file using the loading utility
synthesizer = load_synthesizer(filepath='my_synthesizer.pkl')
```

This prints an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/npatki/Documents/DataCebo/misc/check-mcp/env/lib/python3.12/site-packages/sdv/utils/utils.py", line 176, in load_synthesizer
    check_sdv_versions_and_warn(synthesizer)
  File "/Users/npatki/Documents/DataCebo/misc/check-mcp/env/lib/python3.12/site-packages/sdv/_utils.py", line 276, in check_sdv_versions_and_warn
    if synthesizer._fitted:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'DayZSynthesizer' object has no attribute '_fitted'
```

### Root Cause
This [`check_sdv_versions_and_warn`](https://github.com/sdv-dev/SDV/blob/main/sdv/_utils.py#L262) function is meant to proactively warn the user if a synthesizer is being loaded into a different, potentially incompatible, version of SDV (based on where it was created). But incorrectly assumes that all synthesizers _must_ have an `_fitted` attribute, which is not true of the DayZSynthesizer.

### PR DESCRIPTION
**Pull request by R-Palazzo**
Resolve #2698
CU-86b6yk3tb

Tested on Enterprise and it worked:

Screenshot 2025-10-15 at 15 14 24

### CODE REVIEW

**Comment by sdv-team** [comment]
Task linked: [CU-86b6yk3tb SDV - Unable to load the DayZSynthesizer after saving it #2698](https://app.clickup.com/t/86b6yk3tb)

File: sdv/_utils.py [hunk 1]
```diff
@@ -273,7 +273,7 @@ def check_sdv_versions_and_warn(synthesizer):
     """
     current_community_version = getattr(version, 'community', None)
     current_enterprise_version = getattr(version, 'enterprise', None)
-    if synthesizer._fitted:
+    if synthesizer.__class__.__name__ != 'DayZSynthesizer' and synthesizer._fitted:
```
Comment (frances-h) [inline sdv/_utils.py]: Should we just change this to a generic `getattr` in case we ever run into this problem with a new synthesizer again?

**Review by fealho — APPROVED** [review]
